swagger: "2.0"
info:
  title: "Sample API"
  description: "Sample API"
  version: "1.0.0"

basePath: "/api"
tags:
- name: "Post"
  description: "Post"

definitions:
  Post:
    type: 'object'
    properties:
      text:
        description: Text
        type: string

paths:
  /posts:
    post:
      tags:
      - "Post"
      summary: Create post
      consumes:
      - "application/json"
      produces:
      - "application/json"
      requestBody:
        required: true
        content:
          application/json:
            schema
      parameters:
      - name: "text"
        in: "body"
        description: "Text"
        schema:
          type: object
          required:
            - text
          properties:
            message:
              type: string

      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Post"
        400:
          description: "Invalid"

    get:
      tags:
      - Post
      summary: Get posts
      produces:
      - "application/json"

      responses:
        200:
          description: "successful operation"
          type: array
          schema:
            $ref: "#/definitions/Post"
